<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\src\BlazeForms.Core\BlazeForms.Core.csproj" />
    <ProjectReference Include="..\..\src\BlazeForms.Renderer\BlazeForms.Renderer.csproj" />
    <ProjectReference Include="..\..\src\BlazeForms.Designer\BlazeForms.Designer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.8.0" />
  </ItemGroup>

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
